#!/usr/bin/env python
""" 
Adds a collision object representing the table to the planning scene
Loads a list of waypoints from the parameter server (if waypoints don't exist, the list is empty)

PUBLISHERS:
  + /move_group/display_planned_path moveit_msgs.msg.DisplayTrajectory ~ 

SERVICES:
  + /reset reset ~ Spawns an obstacle collision object in Rviz at a specified location; optionally clears waypoints on parameter server 
  + /test test ~
"""
import sys
import rospy
from std_srvs.srv import EmptyResponse
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from arm_move.srv import reset, step, follow, resetResponse
from moveit_commander.conversions import pose_to_list

