#!/usr/bin/env python

import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image
import cv2

class GetData(object):
    def __init__(self):
        self._bridge = CvBridge()
        self._sub = rospy.Subscriber("/camera/aligned_depth_to_color/image_raw/image_topics", Image, self.callback)
        rospy.logerr('init')


    def callback(self,data):
        cv_image = self._bridge.imgmsg_to_cv2(data, "bgr8")
        rospy.logerr('callback')
        rospy.logerr(cv_image)



if __name__=="__main__":
    rospy.init_node("perception")
    rospy.logerr('main')
    c = GetData()
    rospy.spin()
