#!/usr/bin/env python
""" This node is not in use. It contains the infrastructure for displaying a GUI scoreboard to show the user
    if a goal has been scored or the robot registered a block. The structure of the scoreboard is in place and
    can be successfully displayed, but it has currently not yet been integrated with the main code. In the
    motion_control node, goals are successfully counted, but blocks have not yet been accounted for.

    SUBSCRIBERS:
        scores (robokeeper/Scores) - number of goals scored (human) and number of blocks (robot)

    PUBLISHERS:
        None
    
    SERVICES:
        None
"""

import rospy
from robokeeper.msg import Scores
from tkinter import Tk, Canvas

# Define useful parameters
size_of_board = 600
rows = 10
cols = 10
DELAY = 100
symbol_size = (size_of_board / 3 - size_of_board / 8) / 2
symbol_thickness = 2
PURPLE_COLOR = "#59118e"

class Scoreboard:
    def __init__(self):
        self.window = Tk()
        self.window.title("Robokeeper")
        self.canvas = Canvas(self.window, width=size_of_board*2, height=size_of_board)
        self.canvas.pack()
        self.begin = False
        self.human = 0
        self.robot = 0

        rospy.Subscriber("/scores", Scores, self.callback_score)
    
    def callback_score(self, msg:Scores):
        """ 
        Function: Callback function for the score subscriber
        Args:
            msg (Scores) - goals scored (msg.human) and blocks (msg.robot)
        Returns:
            None
        """
        self.human = msg.human
        self.robot = msg.robot

        self.mainloop()

    def initialize_board(self):
        """ 
        Function: Creates base scoreboard
        """
        self.board = []
        for i in range(rows):
            for j in range(cols):
                self.board.append((i, j))

    def mainloop(self):
        """ 
        Function: Updates displayed window and runs display_scores continously
        """
        while True:
            self.window.update()
            self.display_scores()

    def display_scores(self, human, robot):
        """ 
        Function: Creates specified text and displays in on created canvas
        """
        robot_text = "ROBOT \n"
        human_text = "HUMAN \n"

        self.canvas.create_text(
            size_of_board*2*0.3,
            size_of_board*0.25,
            font=("Helvetica 60"),
            fill=PURPLE_COLOR,
            text=human_text,
        )

        # score_text = str(score)
        self.canvas.create_text(
            size_of_board*2*0.7,
            size_of_board*0.25,
            font=("Helvetica 60"),
            fill=PURPLE_COLOR,
            text=robot_text,
        )

        self.canvas.create_text(
            size_of_board*2*0.3,
            size_of_board*0.65,
            font=("Helvetica 300"),
            fill=PURPLE_COLOR,
            text=str(human),
        )

        self.canvas.create_text(
            size_of_board*2*0.7,
            size_of_board*0.65,
            font=("Helvetica 300"),
            fill=PURPLE_COLOR,
            text=str(robot),
        )

if __name__=="__main__":
    rospy.init_node("scorekeeper")
    Scoreboard()
    rospy.spin()