#!/usr/bin/env python

import numpy as np
import rospy
from robokeeper.msg import Scores
from robokeeper_library.scoreboard import Scoreboard

class Scorekeeper():
    def __init__(self):
        rospy.Subscriber("/scores", Scores, self.callback_score)

    def callback_score(self, msg:Scores):
        Scoreboard.mainloop(msg.human, msg.robot)
